version: 2.1

jobs:
  build-and-test:
    docker:
    - image: circleci/python:3.7
    - image: localstack/localstack
      environment:
        SERVICES: iam,sts
    steps:
    - checkout
    - run:
        name: Install APT dependencies
        command: |
          sudo apt-get update
          sudo apt-get install -y python-dev libsasl2-dev gcc
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt" }}
    - run:
        name: Install PIP dependencies
        command: ./bin/setup.sh
    - save_cache:
        key: pip-{{ checksum "requirements.txt" }}
        paths:
        - ./.env/lib/
    - run:
        name: Test
        command: ./bin/test.sh
    - run:
        name: Upload coverage
        command: |
          . .env/bin/activate
          python3 -m codecov

workflows:
  version: 2
  main:
    jobs:
    - build-and-test:
        filters:
          branches:
            only: /.*/
